web:
    build: .
    command: jekyll serve --watch --drafts --force_polling --config _config.dev.yml
    ports:
        - "4000:4000"
    volumes:
        - .:/src
    environment:
        - INSTANCE_TYPE=web-server
